version: "3"
services:
  cache:
    container_name: cache
    image: redis:6.2
    ports:
      - 6379:6379
  back:
    container_name: nest
    build: ./nestjs
    volumes:
      - ./nestjs:/nestjs
    ports:
      - 3000:3000
    depends_on:
      - cache
    links:
      - cache
  python:
    build: ./python
    tty: true
    depends_on:
      - cache
      - back
    links:
      - cache
