networks:
    queue-network:
    back-network:

services:
  cache:
    container_name: cache
    image: redis:6.2
    networks:
        - queue-network
  back:
<<<<<<< HEAD
    container_name: nest-redis
=======
    container_name: nest
>>>>>>> 4fc972c8d3d7d6d0609f909294ba720e6f155ec0
    build: ./nestjs
    volumes:
      - ./nestjs:/nestjs
    ports:
      - 3000:3000
    depends_on:
      - cache
    networks:
        - queue-network
        - back-network
  python:
    image: python:3.9
    volumes:
        - ./python:/python
    working_dir: /python
    command: bash ./start_python.sh
    depends_on:
      - cache
      - back
    networks:
        - queue-network
